function Get-DataGridSelectionSchema {
    <#
    .SYNOPSIS
        Resolves the selected DataGrid columns to the property names and types the clipboard
        formatters need.

    .DESCRIPTION
        The only part of the #103 copy path that reads the grid, so everything downstream of it is
        testable without a UI.

        Two things it gets right that the pre-#103 code did not:

          * It carries the BINDING PATH, not the header. Headers pass through Invoke-SanitizeJsonKeys
            and the grid's own header escaping, so a header is not reliably the name of the property
            it displays. SortMemberPath is what AutoGenerateColumns sets from the property itself.
          * It leaves the value alone. OnCopyingCellClipboardContent renders a cell to text, and
            rendering to text under the thread culture is what discards the type information this
            whole change exists to keep.

        SqlType is the seam for priority 1 of the issue's resolution order - the declared type from
        the cached SQL schema. Resolving it needs the executed query's tables and aliases parsed, so
        it is not delivered here and the property is always $null. Downstream code already reads and
        honours it, so adding the lookup later is a change to this function alone.

    .PARAMETER DataGrid
        The DataGrid to read. Defaults to the query result grid.

    .OUTPUTS
        [PSCustomObject[]] one entry per selected column, in display order, with Header,
        PropertyName and SqlType.

    .EXAMPLE
        $ColumnSchema = Get-DataGridSelectionSchema

    .NOTES
    #>

    [CmdLetBinding()]
    [OutputType([PSCustomObject[]])]
    param(
        [Parameter(Mandatory = $false, Position = 0)]
        $DataGrid
    )

    $Script:Tracer::WriteLine(("{0}: Function: {1} - Caller: {2}({3}) - Command: {4} - Parameters: {5}" -f $($Script:RunTimeConfig.ApplicationName), $($MyInvocation.MyCommand.Name), $($MyInvocation.ScriptName).Split("\")[-1], $($MyInvocation.ScriptLineNumber), $MyInvocation.Statement, "<suppressed: carries grid content>"))

    if ($null -eq $DataGrid) {
        $DataGrid = $Script:MainForm.Elements.DataGridQueryResult
    }

    if ($null -eq $DataGrid -or $null -eq $DataGrid.SelectedCells -or $DataGrid.SelectedCells.Count -le 0) {
        return @()
    }

    $SelectedColumnSet = [System.Collections.Generic.HashSet[object]]::new()
    $SelectedColumns = [System.Collections.Generic.List[object]]::new()
    foreach ($SelectedCell in $DataGrid.SelectedCells) {
        if ($SelectedColumnSet.Add($SelectedCell.Column)) {
            $SelectedColumns.Add($SelectedCell.Column)
        }
    }

    $ColumnSchema = [System.Collections.Generic.List[object]]::new()
    foreach ($Column in @($SelectedColumns | Sort-Object -Property DisplayIndex)) {
        $Header = "{0}" -f $Column.Header

        # SortMemberPath first, header second. The fallback matters for a column that was not
        # autogenerated and therefore has no binding path; for those the header is all there is.
        $PropertyName = $Column.SortMemberPath
        if ([string]::IsNullOrWhiteSpace($PropertyName)) {
            $PropertyName = $Header
        }

        $ColumnSchema.Add([PSCustomObject]@{
                Header       = $Header
                PropertyName = $PropertyName
                SqlType      = $null
            })
    }

    return @($ColumnSchema)
}
