# End-to-end validation of "Copy as SQL/PowerShell array" (issue #103), driving the REAL DataGrid.
#
# The unit tests under tests\*.Tests.ps1 cover every literal and shape decision against a stubbed
# grid. Exactly one claim cannot be made there, and it is the one this file exists for:
#
#   an autogenerated WPF column's SortMemberPath really is the name of the row property it displays.
#
# Get-DataGridSelectionSchema is built on that. If it were not true, every value would be read as
# $null and the whole feature would copy a list of NULLs - with a stubbed grid the tests would still
# pass, because the stub is the thing that would be wrong.
#
# Clipboard::SetText itself is deliberately not exercised: the clipboard is machine-global shared
# state and is not reliably available to an unattended session, so asserting on it would make this
# suite flaky for no extra coverage. Everything up to that call is driven here.

E2ESuite -Name "ArrayCopy" -Body {

    # The columns from issue #103's failure table: an int, an nvarchar holding digits, an nvarchar
    # holding a leading-zero code, a bit, a datetime, a NULL column and a uniqueidentifier.
    $script:E2EArrayCopyRows = @(
        [pscustomobject]@{ Id = 900; Number = "12345"; Code = "007"; Deleted = $false; CreateTime = "2019-11-20T13:55:09"; ParentID = $null; UID = "0f6a1b3c-1111-4a2b-9c01-a00000000900" }
        [pscustomobject]@{ Id = 901; Number = "12346"; Code = "008"; Deleted = $true; CreateTime = "2019-11-20T13:55:09"; ParentID = $null; UID = "0f6a1b3c-1111-4a2b-9c01-a00000000901" }
    )

    function script:Initialize-ArrayCopyGrid {
        <#
            Connects and executes so the result grid is populated and its columns generated.

            Returns nothing on purpose: the helpers here call into driver functions that write to
            the pipeline, so anything returned would arrive at the caller as an array with the grid
            somewhere inside it. Each case reads the grid from Get-E2EElements instead.
        #>
        Reset-E2EScenario
        Set-E2EConnectionFields
        Invoke-E2EConnectAndWait

        $script:E2EResultRows = $script:E2EArrayCopyRows
        Select-E2EQuery -Name "TestQuery - 100" | Out-Null
        Invoke-E2EExecuteAndWait

        # AutoGenerateColumns only produces columns during a layout pass, so force one before any
        # case reads Columns or SortMemberPath.
        $Grid = (Get-E2EElements).DataGridQueryResult
        $Grid.UpdateLayout()
        Invoke-E2EFlushDispatcher | Out-Null
    }

    function script:Get-ArrayCopyGrid {
        return (Get-E2EElements).DataGridQueryResult
    }

    function script:Get-ArrayCopyColumn {
        param(
            $Grid,
            [string]$Header
        )

        return @($Grid.Columns | Where-Object { ("{0}" -f $_.Header) -eq $Header })[0]
    }

    function script:Select-ArrayCopyCell {
        <#
            Selects every cell of the named columns, the way a user dragging across those columns
            would. Returns nothing, for the reason given in Initialize-ArrayCopyGrid.
        #>
        param(
            $Grid,
            [string[]]$ColumnHeader
        )

        $Grid.SelectedCells.Clear()
        foreach ($Item in $Grid.Items) {
            foreach ($Header in $ColumnHeader) {
                $Column = Get-ArrayCopyColumn -Grid $Grid -Header $Header
                if ($null -ne $Column) {
                    $Grid.SelectedCells.Add([System.Windows.Controls.DataGridCellInfo]::new($Item, $Column)) | Out-Null
                }
            }
        }

        Invoke-E2EFlushDispatcher | Out-Null
    }

    E2ECase -Name "an autogenerated column's SortMemberPath is the row property name, which is what the copy path binds to" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        E2EAssertEqual 7 (@($Grid.Columns).Count) "the grid should autogenerate one column per fixture property"

        foreach ($Header in @("Id", "Number", "Code", "Deleted", "CreateTime", "ParentID", "UID")) {
            $Column = @($Grid.Columns | Where-Object { ("{0}" -f $_.Header) -eq $Header })[0]
            E2EAssertTrue ($null -ne $Column) "a column should be generated for '$Header'"
            E2EAssertEqual $Header ("{0}" -f $Column.SortMemberPath) "SortMemberPath for '$Header' should be the row property name"
        }
    }

    E2ECase -Name "the resolved selection schema reads real values off the real rows" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("Id")

        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)
        E2EAssertEqual 1 $Schema.Count "one column should be resolved"
        E2EAssertEqual "Id" $Schema[0].PropertyName "the property name should come from the binding path"

        # The value must arrive typed, not rendered. This is the line the pre-#103 code got wrong.
        $Value = $Grid.Items[0].$($Schema[0].PropertyName)
        E2EAssertTrue ($null -ne $Value) "reading the row by the resolved property name should not return null"
        E2EAssertEqual "Integer" (Get-QueryResultValueKind -Value $Value) "an int column should resolve to Integer, not String"
    }

    E2ECase -Name "an nvarchar column holding digits copies as quoted strings, not as integers (criteria 1 and 2)" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        $Setting = Get-ArrayCopySetting

        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("Number")
        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)
        $Sql = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "SqlArray" -Setting $Setting

        E2EAssertTrue ($Sql -like "*'12345'*") "an all-digit nvarchar value should be quoted"
        E2EAssertTrue ($Sql -notlike "*    12345,*") "it should not be emitted as a bare integer"

        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("Code")
        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)
        $Sql = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "SqlArray" -Setting $Setting

        E2EAssertTrue ($Sql -like "*'007'*") "a leading-zero code should survive the copy intact"
    }

    E2ECase -Name "a bit column copies as 1/0 for SQL and `$true/`$false for PowerShell (criterion 4)" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        $Setting = Get-ArrayCopySetting

        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("Deleted")
        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)

        $Sql = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "SqlArray" -Setting $Setting
        E2EAssertEqual "(`r`n    0,`r`n    1`r`n)" $Sql "a bit column should copy as 1/0"

        $PowerShell = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "PowerShellArray" -Setting $Setting
        E2EAssertEqual "@(`r`n    `$false,`r`n    `$true`r`n)" $PowerShell "a bit column should copy as `$false/`$true"
        E2EAssertTrue ($PowerShell -notlike "*'False'*") "'False' is truthy in PowerShell and must never be emitted"
    }

    E2ECase -Name "a NULL column copies as NULL and warns about IN-list semantics (criterion 6)" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        $Setting = Get-ArrayCopySetting

        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("ParentID")
        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)

        Clear-E2ELog
        $Sql = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "SqlArray" -Setting $Setting

        E2EAssertEqual "(`r`n    NULL,`r`n    NULL`r`n)" $Sql "a NULL column should copy as NULL, never as an empty string"
        E2EAssertTrue (@(Get-E2ELogMessages | Where-Object { $_ -like "*silently excludes*" }).Count -ge 1) "copying NULLs should warn about IN-list semantics"
    }

    E2ECase -Name "a multi-column selection produces a joinable VALUES constructor with per-column types (criteria 3 and 9)" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        $Setting = Get-ArrayCopySetting

        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("Id", "Number")
        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)

        $Sql = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "SqlArray" -Setting $Setting
        E2EAssertEqual "(VALUES`r`n    (900, '12345'),`r`n    (901, '12346')`r`n) AS t ([Id], [Number])" $Sql "Id should stay numeric while Number stays quoted"

        $PowerShell = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "PowerShellArray" -Setting $Setting
        $RoundTrip = @(& ([ScriptBlock]::Create($PowerShell)))
        E2EAssertEqual 2 $RoundTrip.Count "the generated PowerShell should parse into two rows"
        E2EAssertEqual "12345" ("{0}" -f $RoundTrip[0].Number) "the round-tripped Number should keep its value"
    }

    E2ECase -Name "the copied IN list executes against the mock and matches the rows it came from (criterion 8)" -Body {
        Initialize-ArrayCopyGrid
        $Grid = Get-ArrayCopyGrid
        $Setting = Get-ArrayCopySetting

        Select-ArrayCopyCell -Grid $Grid -ColumnHeader @("Id")
        $Schema = @(Get-DataGridSelectionSchema -DataGrid $Grid)
        $Sql = Format-QueryResultSelection -Row @($Grid.Items) -ColumnSchema $Schema -OutputFormat "SqlArray" -Setting $Setting

        # Paste the generated list back into a query and run it through the real execute path, which
        # is the test that the produced text is usable rather than merely well shaped.
        $script:E2EEditorText = "SELECT * FROM tblObject WHERE Id IN {0}" -f $Sql
        Invoke-E2EExecuteAndWait

        E2EAssertEqual 2 (@((Get-E2EElements).DataGridQueryResult.ItemsSource).Count) "executing the pasted IN list should return the fixture rows"
        E2EAssertTrue ($script:E2EEditorText -like "*IN (*900,*") "the executed query should carry the unquoted integer list"
    }

    E2ECase -Name "ArrayCopyUseColumnSchema = false restores the pre-#103 output (criterion 11)" -Body {
        # The escape hatch, exercised through the same rendered-text values Copy-DataGridToClipboard
        # feeds it.
        $Legacy = Format-SniffedArrayLiteral -CellValue @("900", "901") -OutputFormat "SqlArray"
        E2EAssertEqual "(`r`n    900,`r`n    901`r`n)" $Legacy "the legacy path should be unchanged"

        $Legacy = Format-SniffedArrayLiteral -CellValue @("007") -OutputFormat "SqlArray"
        E2EAssertEqual "(`r`n    007`r`n)" $Legacy "the legacy path should still sniff, which is why it is not the default"
    }
}
